# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-app
  labels:
    app: fastify-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastify-app
  template:
    metadata:
      labels:
        app: fastify-app
    spec:
      containers:
      - name: fastify-app
        image: olehmuz/fastify-app:latest
        ports:
        - containerPort: 3005
        env:
        - name: MONGO_URI
          value: mongodb+srv://olehmuz87:Oo2SCJnyiiJgH91Y@capacity-db.mfn0b.mongodb.net/?retryWrites=true&w=majority&appName=Capacity-db
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: fastify-app-service
spec:
  selector:
    app: fastify-app
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
  type: LoadBalancer
