replicaCount: 1

image:
  repository: olehmuz/fastify-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080

env:
  MONGO_URI: "mongodb+srv://olehmuz87:Oo2SCJnyiiJgH91Y@capacity-db.mfn0b.mongodb.net/?retryWrites=true&w=majority&appName=Capacity-db"
